port: /dev/ttyUSB1
baud: 500000
scan_duration: 0.025 
scan_cycle_time: 0.040 
publish_frequency: 10
inverted: true
frame_id: /laserfront_link
scan_id: 8
start_scan: 0
stop_scan: 541
scan_intervals: [[-2.35, 2.35]]
#scan_intervals: [[-1.3526, 1.361357]] #[rad] these intervals are included to the filtered scan
translation: [0.377, -0.341, 0.]
orientation: [0., 0., 5.498]
fields: 
  '1':
    scale: 0.01
    start_angle: -2.35619449
    stop_angle: 2.35619449
