activeSensor: [true, true, true, true, true]
frameName: ["frontR","frontM","frontL","rearR","rearL"]
radiationType: [1, 1, 1, 1, 1]
min_range: [0.3, 0.3, 0.3, 0.3, 0.3]
max_range: [2.4, 2.4, 2.4, 2.4, 2.4]
field_of_view: [1.05, 1.05, 1.05, 1.05, 1.05]
translation_x: [0.357, 0.357, 0.357, -0.357, -0.357]
translation_y: [-0.160, 0., 0.160, -0.115, 0.115]
translation_z: [0.377, 0.377, 0.377, 0.374, 0.374]
orientation_yaw: [0., 0., 0., 0., 0.]
orientation_pitch: [-0.52, -0.52, -0.52, -2.62, -2.62]
orientation_roll: [3.14, 3.14, 3.14, 3.14, 3.14]
