# Common settings for costmaps
# May be overwritten in specific global and local costmap files

# Global Filtering Parameters
obstacle_range: 2.5   # The default maximum distance from the robot at which an obstacle will be inserted
                      # into the cost map in meters. This can be over-ridden on a per-sensor basis. Default: 2.5
raytrace_range: 4.0   # The default range in meters at which to raytrace out obstacles from the
                      # map using sensor data. This can be over-ridden on a per-sensor basis. Default: 3.0

#footprint: [[0.55,0.5],[0.55,-0.5],[-0.55,-0.5],[-0.55,0.5]]
robot_radius: 0.40
# inflation_radius: 0.35