base_global_planner: global_planner/GlobalPlanner

GlobalPlanner:
  neutral_cost: 50 # Leave default values as it might not be able to find a path
                   # through narrow corridors.
  planner_frequency: 10
