global_costmap: 
  # Coordinate frame and tf parameters
  global_frame: map         
  robot_base_frame: base_link
  transform_tolerance: 1.5  # Specifies the delay in transform (tf) data that is tolerable in seconds.
                            # This parameter serves as a safeguard to losing a link in the tf tree while
                            # still allowing an amount of latency the user is comfortable with to exist
                            # in the system. For example, a transform being 0.2 seconds out-of-date may
                            # be tolerable, but a transform being 8 seconds out of date is not. If the
                            # tf transform between the coordinate frames specified by the global_frame
                            # and robot_base_frame parameters is transform_tolerance seconds older than
                            # ros::Time::now(), then the navigation stack will stop the robot. Default: 0.2

  # Rate parameters
  update_frequency: 0.5     # The frequency in Hz for the map to be updated. Default 5.0
  # publish_frequency: 1.0    # The frequency in Hz for the map to be publish display information. Default: 0.0   

  # Map management parameters
  rolling_window: false
  static_map: true
    

  plugins:
    - {name: static_layer,         type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,       type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,      type: "costmap_2d::InflationLayer"}
    - {name: social_layer,         type: "social_navigation_layers::ProxemicLayer"}
    - {name: social_pass_layer,    type: "social_navigation_layers::PassingLayer"}

  # Layer Definitions
  static_layer:
    map_topic: /map
    #subscribe_to_updates: true

  inflation_layer:
    # cost_scaling_factor: 10.0 # Default: 10.0
    inflation_radius: 0.5     # A high inflation radius in the global costmap helps the robot go more
                              # in the middle of areas, instead of going very close to objects and walls.
                              # The robot can still go through narrow areas, just at a higher cost, so it
                              # may find a longer and more open route.

  social_layer: 
    cutoff: 226        # Default 10
    amplitude: 255     # Default 77.0
    covariance: 200.0    # Default 0.25
    factor: 100         # Default 5
