TebLocalPlannerROS:
 # The underlying method called Timed Elastic Band locally optimizes the
 # robot's trajectory with respect to trajectory execution time, separation
 # from obstacles and compliance with kinodynamic constraints at runtime.
 # See all parameters and default values here:
 # http://wiki.ros.org/teb_local_planner


  # Miscellaneous
  odom_topic: odom
  map_frame: map

  # Robot Configuration
  max_vel_theta: 0.3 # 0.3
  max_vel_x: 0.4 #0.4
  max_vel_x_backwards: 0.2

  footprint_model:
   type: "circular"
   radius: 0.55 # for type "circular"

  # Trajectory Configuration
  dt_ref: 0.5 #Increase to lower computations. Default: 0.3

  # Obstacle and Costmap converter plugin
  min_obstacle_dist: 0.2  # Default 0.5 
  include_costmap_obstacles: True 
  costmap_obstacles_behind_robot_dist: 5.0
  obstacle_poses_affected: 10 # Decrease to lower computations. Default: 30
  inflation_dist: 1.08     # Default 0.6
  #include_dynamic_obstacles: true # Enabling this could cause the robot to recognise walls as dynamic obstacles,
                                   # due to incorret aligment of laser scans.

  costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH"
  #costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSRANSAC"
  #costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSMCCH"
  #costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSConcaveHull"
  #costmap_converter_plugin: "" # deactivate plugin
  costmap_converter_spin_thread: true
  costmap_converter_rate: 10
  
  # Optimization
  no_inner_iterations: 3 # Decrease to lower computations. Default: 5
  no_outer_iterations: 2 # Decrease to lower computations. Default: 4
  penalty_epsilon: 0.1
  weight_obstacle: 10
  weight_optimaltime: 0.1
  weight_inflation: 0.2
  weight_kinematics_forward_drive: 100

  # Parallel planning
  enable_homotopy_class_planning: true
  max_number_classes: 4 
  max_global_plan_lookahead_dist: 5 #Fit this to detectable range of vision
