activeSensor: [true, true, true, true]
frameName: ["base_us1","base_us2","base_us3","base_us4"]
radiationType: [1, 1, 1, 1]
min_range: [0.3, 0.3, 0.3, 0.3]
max_range: [2.4, 2.4, 2.4, 2.4]
field_of_view: [1.05, 1.05, 1.05, 1.05]
translation_x: [0., 0., 0., 0.]
translation_y: [0., 0., 0., 0.]
translation_z: [0., 0., 0., 0.]
orientation_yaw: [0., 0., 0., 0.]
orientation_pitch: [0., 0., 0., 0.]
orientation_roll: [0., 0., 0., 0.]
