# Parameters for neo_teleop
axis_linear_x: 1
axis_linear_y: 0
axis_angular_z: 2
scale_angular_z: 0.3 # Original: 0.6, lowered to make the robot move less erratically (slower)
scale_linear_x: 0.3  # Original: 0.6
scale_linear_y: 0.3  # Original: 0.6
smooth: true

deadman_button: 5   # index of the button on the controller wich has to be pushed while driving
                    # index 5 = button 6 (RT)
timeOut: 0.1        # timeout to stop robot if no command is recived for X seconds and
                    # deadman_button is not pushed